# src/config/config.yaml

dataset:
  name: mnist  # Options: 'mnist', 'cifar10', 'custom'

model:
  name: resnet  # Changed from 'vit' to 'resnet'
  num_labels: 10

training:
  batch_size: 32
  epochs: 1
  learning_rate: 1e-4

federated_learning:
  num_clients: 5
  rounds: 5
  fraction_fit: 0.6
  num_shards: 50
  num_samples: 100
  partition_type: non_iid  # Options: 'iid', 'non_iid'

fedbary:
  use_validation: true
